### ISSUE TITLE
May I move trailer_read and trailer_write into the public API?

### ISSUE THREAD

**Issue by snarkmaster** [edmonds/mtbl#1]
It's really useful to be able to query t.bytes_keys, t.bytes_values, since this lets me pre-allocate memory when I want to load the whole mtbl file into RAM.

**Comment by edmonds** [comment]
Hi, snarkmaster:

This repo is out of date. Mainline development takes place over here: https://github.com/farsightsec/mtbl. I'd recommend re-opening your issue there.
